export enum FirestoreType {
  IS_PENDING = "IS_PENDING",
  ADDED_USER = "ADDED_USER",
  ADDED_DOC = "ADDED_DOC",
  DELETED_DOC = "DELETED_DOC",
  ADDED_CATEGORY = "ADDED_CATEGORY",
  DELETED_CATEGORY = "DELETED_CATEGORY",
  UPDATED_CATEGORY = "UPDATED_CATEGORY",
  ERROR = "ERROR",
}
