import {
  LOGIN_BELOW_TEXTS,
  SIGNUP_BELOW_TEXTS,
  INSPIRATION_BELOW_TEXTS,
  GO_BACK_BELOW_TEXTS,
} from "./below-box-texts";

import {
  COLLECTION_USERS,
  COLLECTION_TRANSACTIONS,
  FIELD_UID,
  FIELD_CREATED_AT,
  QUERY_OPERATOR_DESC,
  QUERY_OPERATOR_EQUAL,
} from "./firebase";

import {
  LOGIN_FORM_FIELDS,
  SIGN_UP_FORM_FIELDS,
  UPDATE_PROFILE_FORM_FIELDS,
} from "./form-fields";

export {
  LOGIN_BELOW_TEXTS,
  SIGNUP_BELOW_TEXTS,
  INSPIRATION_BELOW_TEXTS,
  GO_BACK_BELOW_TEXTS,
  COLLECTION_USERS,
  COLLECTION_TRANSACTIONS,
  FIELD_UID,
  FIELD_CREATED_AT,
  QUERY_OPERATOR_DESC,
  QUERY_OPERATOR_EQUAL,
  LOGIN_FORM_FIELDS,
  SIGN_UP_FORM_FIELDS,
  UPDATE_PROFILE_FORM_FIELDS,
};
