import {
  LOGIN_BELOW_TEXTS,
  SIGNUP_BELOW_TEXTS,
  INSPIRATION_BELOW_TEXTS,
  GO_BACK_BELOW_TEXTS,
} from "./below-box-texts";

import {
  LOGIN_FORM_FIELDS,
  SIGN_UP_FORM_FIELDS,
  UPDATE_PROFILE_FORM_FIELDS,
} from "./form-fields";

export {
  LOGIN_BELOW_TEXTS,
  SIGNUP_BELOW_TEXTS,
  INSPIRATION_BELOW_TEXTS,
  GO_BACK_BELOW_TEXTS,
  LOGIN_FORM_FIELDS,
  SIGN_UP_FORM_FIELDS,
  UPDATE_PROFILE_FORM_FIELDS,
};
