name: Deploy to Firebase

on:
  push:
    branches:
      - master
      - development

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install

      - name: Build application
        run: npm run build

      - name: Deploy to Firebase
        run: |
          if [ "${{ github.ref }}" == "refs/heads/master" ]; then
            firebase use prod --token ${{ secrets.FIREBASE_TOKEN }}
          else
            firebase use dev --token ${{ secrets.FIREBASE_TOKEN }}
          fi
          firebase deploy --only hosting
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}